import React from 'react';

import style from './betaTOS.css';
import {Grid, Row, Col} from '../layout';

const BetaTOS = React.createClass({
  render() {
    return (
      <div>
        <Grid>
          <Row>
            <Col xs={12}>
            <h1 className={style.p}>USER AGREEMENT</h1>
            <ol>
              <li className={style.p}><strong>Grant of License and Restrictions</strong>.  Subject to the terms hereof and any applicable user/use limitations, Opsee will provide User with access to the Services through the internet.  The Services are subject to modification from time to time at Opsee’s sole discretion, for any purpose deemed appropriate by Opsee.  Opsee will use reasonable efforts to give User prior written notice of any such modification. Opsee reserves the right to suspend User’s access to the Services: (i) for scheduled or emergency maintenance, or (ii) in the event User is in breach of this Agreement, including failure to use the Services and proactively communicate with Opsee.  User’s use of the Services will be limited to one (1) authorized user per account.  User will not, and will not permit any third party to: reverse engineer, decompile, disassemble or otherwise attempt to discover the source code, object code or underlying structure, ideas or algorithms of the Services or any software, documentation or data related to the Services (“Software”) (provided that reverse engineering is prohibited only to the extent such prohibition is not contrary to applicable law); modify, translate, or create derivative works based on the Services or Software; use the Services or Software for timesharing or service bureau purposes or for any purpose other than its own use; or use the Services or Software other than in accordance with this Agreement and in compliance with all applicable laws and regulations (including but not limited to any European privacy laws), intellectual property, consumer and child protection, obscenity or defamation. User will cooperate with Opsee in connection with the performance of this Agreement by making available such personnel and information as may be reasonably required, and taking such other actions as Opsee may reasonably request.  User will also cooperate with Opsee in establishing a password or other procedures for verifying that only designated employees of User have access to any administrative functions of the Services.  User will designate an employee who will be responsible for all matters relating to this Agreement (“Primary Contact”).  User may change the individual designated as Primary Contact at any time by providing written notice to Opsee. User will be responsible for maintaining the security of User’s account, passwords (including but not limited to administrative and user passwords) and files, and for all uses of User account with or without User’s knowledge or consent.  User’s use of Opsee’s website and/or services is at all times subject to <a href="/terms-of-use">Opsee’s terms of service and privacy policy</a> (the “Website Terms”). USER ACKNOWLEDGES THAT THE SERVICES MAY INCLUDE FEATURES TO PREVENT USE OR ACCESS INCONSISTENT HEREWITH.</li>
              <li className={style.p}><strong>Third-Party Services</strong>.  User acknowledges and agrees that the Services operate on or with or using application programming interfaces (APIs) and/or other services operated or provided by third parties (“Third Party Services”). Opsee is not responsible for the operation of any Third Party Services nor the availability or operation of the Services to the extent such availability and operation is dependent upon Third Party Services.  User is solely responsible for procuring any and all rights necessary for it to access Third Party Services and for complying with any applicable terms or conditions thereof.  Opsee does not make any representations or warranties with respect to Third Party Services or any third party providers.  Any exchange of data or other interaction between User and a third party provider is solely between User and such third party provider and is governed by such third party’s terms and conditions. In addition, access to the Services may require the User to install certain software applications.  User agrees to be bound by any end-user software agreements that govern the installation and use of such client software applications.</li>
              <li className={style.p}><strong>Fees</strong>.  Many of the Services are currently free.  However, Opsee reserves the right to charge for certain or all Services in the future, including new Services added.  Opsee will notify User before any Services User is then using begin carrying a fee, and if User wishes to continue using such Services, User shall pay all applicable fees for such Services. If User enrolls in any premium services offered by Opsee (the “Premium Services”), User will be charged the applicable subscription fee set forth on the Opsee website (the “Subscription Fee”) in advance, to the method of payment provided upon enrollment in the Premium Services.   Subscription Fees are non-refundable.  User’s enrollment in the Premium Services will be automatically renewed on a monthly basis. User must notify Opsee at least thirty (30) days prior to the auto-renewal date to cancel auto-renewal of the Premium Services for the following month. Opsee may change the Subscription Fee upon notice, but such change will only take effect once User’s then-current Premium Services term has ended.  If User does not consent to such change, User’s only remedy shall be to cancel enrollment in the Premium Services for the following billing period, prior to the expiration of the then-current Premium Services term.  User may cancel its Premium Services subscription at any time, provided that no refunds will be granted for Subscription Fees paid.</li>
              <li className={style.p}><strong>Confidentiality</strong>. User understands that Opsee has disclosed or may disclose information relating to Opsee’s technology or business (hereinafter referred to as “Proprietary Information”), including, without limitation, the software provided for testing and the existence, terms and conditions of this Agreement. User agrees: (i) not to divulge to any third person any such Proprietary Information, (i) to give access to such Proprietary information solely to those employees with a need to have access thereto for purposes of this Agreement, and (iii) to  take the same security precautions to protect against disclosure or unauthorized use of such Proprietary information that User takes with its own proprietary information, but in no event will User apply less than reasonable precautions to protect such Proprietary Information.  Nothing in this Agreement will prevent User from disclosing the Proprietary Information pursuant to any judicial or governmental order, provided that User gives Opsee reasonable prior notice of such disclosure to contest such order. User acknowledges that Opsee does not wish to receive any proprietary information from User, and, unless the parties specifically agree otherwise, Opsee may reasonably presume that any information received from User is not confidential.</li>
              <li className={style.p}><strong>Intellectual Property; Data</strong>.  Except as expressly set forth herein, Opsee alone (and its licensors, where applicable) will retain all intellectual property rights relating to the Service or the Software or any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by User or any third party relating to the Service and/or the Software, all of which are hereby assigned to Opsee.  User will not copy, distribute, reproduce or use any of the foregoing except as expressly permitted under this Agreement.  Notwithstanding the foregoing, User will retain all intellectual property rights in and to the resource availability data obtained by User during its use of the Services (the “Resulting Data”), provided that User hereby grants to Opsee a non-exclusive right to use and freely exploit the Resulting Data to provide, modify, and improve Opsee’s products and services.  In addition to the Resulting Data, Opsee may collect data with respect to and report on the aggregate response rate and other aggregate measures of the Services’ performance and Opsee alone shall retain all intellectual property rights relating thereto.  This Agreement is not a sale and does not convey to User any rights of ownership in or related to the Service or Software, or any intellectual property rights.  Opsee will obtain and process data and/or content provided by or on behalf of User (“User Data”) only to perform its obligations under this Agreement. User and its licensors shall (and User hereby represents and warrants that they do) have and retain all right, title and interest (including, without limitation, sole ownership of) all User Data processed by the Services and the intellectual property rights with respect to such User Data.  If Opsee receives any notice or claim that any User Data, or activities hereunder with respect to any User Data, may infringe or violate rights of a third party (a “Claim”), Opsee may (but is not required to) suspend activity hereunder with respect to such User Data and User will indemnify Opsee from all liability, damages, settlements, attorney fees and other costs and expenses in connection with any such Claim, as incurred.</li>
              <li className={style.p}><strong>Termination; Breach</strong>.  The initial term of this Agreement shall be three (3) months (the “Initial Term”).  Following the Initial Term, this Agreement will renew for successive renewal terms as determined by Opsee and notified in writing to User (each, a “Renewal Term”, and together with the Initial Term, the “Service Term”) unless either party gives the other party notice of non-renewal prior to the end of the then-current term.  Opsee may terminate this Agreement at any time during the Service Term for its convenience by providing written notice to User. Upon any termination, User shall immediately cease all use of the Services.  Except as otherwise expressly provided herein, the terms hereof shall survive any termination.  Termination is not an exclusive remedy and all other remedies will be available whether or not termination occurs.</li>
              <li className={style.p}><strong>Indemnification</strong>.  User hereby agrees to indemnify and hold harmless Opsee against any damages, losses, liabilities, settlements and expenses (including without limitation costs and attorneys’ fees) in connection with any claim or action that arises from an alleged violation of the foregoing or otherwise from User’s use of Services.  Although Opsee has no obligation to monitor the content provided by User or User’s use of the Services, Opsee may do so and may remove any such content or prohibit any use of the Services it believes may be (or alleged to be) in violation of the foregoing.</li>
              <li className={style.p}>WARRANTY DISCLAIMER. THE SERVICES AND PROPRIETARY INFORMATION AND ANYTHING PROVIDED IN CONNECTION WITH THIS AGREEMENT ARE PROVIDED "AS-IS," WITHOUT ANY WARRANTIES OF ANY KIND.  OPSEE (AND ITS AGENTS, AFFILIATES, LICENSORS AND SUPPLIERS) HEREBY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.</li>
              <li className={style.p}><strong>Government Matters</strong>. Notwithstanding anything else, User may not provide to any person or export or re-export or allow the export or re-export of the Services or any software or anything related thereto or any direct product thereof (collectively “Controlled Subject Matter”), in violation of any restrictions, laws or regulations of the United States Department of Commerce, the United States Department of Treasury Office of Foreign Assets Control, or any other United States or foreign agency or authority. Without limiting the foregoing, User acknowledges and agrees that the Controlled Subject Matter will not be used or transferred or otherwise exported or re-exported to countries as to which the United States maintains an embargo (collectively, “Embargoed Countries”), or to or by a national or resident thereof, or any person or entity on the U.S. Department of Treasury’s List of Specially Designated Nationals or the U.S. Department of Commerce’s Table of Denial Orders (collectively, “Designated Nationals”).  The lists of Embargoed Countries and Designated Nationals are subject to change without notice.  Use of the Service is representation and warranty that the user is not located in, under the control of, or a national or resident of an Embargoed Country or Designated National.  The Controlled Subject Matter may use or include encryption technology that is subject to licensing requirements under the U.S. Export Administration Regulations.  As defined in FAR section 2.101, any software and documentation provided by Opsee are “commercial items” and according to DFAR section 252.227 7014(a)(1) and (5) are deemed to be “commercial computer software” and “commercial computer software documentation.”  Consistent with DFAR section 227.7202 and FAR section 12.212, any use modification, reproduction, release, performance, display, or disclosure of such commercial software or commercial software documentation by the U.S. Government will be governed solely by the terms of this Service Agreement and will be prohibited except to the extent expressly permitted by the terms of this Agreement.</li>
              <li className={style.p}><strong>Limitation of Liability</strong>.  IN NO EVENT WILL  OPSEE (OR ANY OF ITS AGENTS, AFFILIATES, LICENSORS OR SUPPLIERS) BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, OR COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THE SERVICES OR ANYTHING PROVIDED IN CONNECTION WITH THIS AGREEMENT, THE DELAY OR INABILITY TO USE THE SERVICES OR ANYTHING PROVIDED IN CONNECTION WITH THIS AGREEMENT OR OTHERWISE ARISING FROM THIS AGREEMENT, INCLUDING WITHOUT LIMITATION, LOSS OF REVENUE OR LOST BUSINESS, OR LOSS OF USE OR LOSS OF DATA, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE, EVEN IF OPSEE HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES.  THE TOTAL LIABILITY OF OPSEE, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE OR STRICT LIABILITY), OR OTHERWISE, WILL NOT EXCEED, IN THE AGGREGATE, ONE HUNDRED DOLLARS.  THE FOREGOING LIMITATIONS WILL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.</li>
              <li className={style.p}><strong>Miscellaneous</strong>.  If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable.  This Agreement is not assignable, transferable or sublicensable by User except with Opsee’s prior written consent, and any attempt to do so will be void.  Opsee may freely transfer and assign any of its rights and obligations under this Agreement.  Both parties agree that this Agreement, together with the Website Terms (to the extent applicable), is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all waivers and modifications must be in a writing signed by both parties, except as otherwise provided herein.  No agency, partnership, joint venture, or employment is created as a result of this Agreement and User does not have any authority of any kind to bind Opsee in any respect whatsoever.  In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover costs and attorneys’ fees.  All notices under this Agreement will be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; and upon receipt, if sent by certified or registered mail (return receipt requested), postage prepaid.  Opsee will not be liable for any loss resulting from a cause over which it does not have direct control.  This Agreement will be governed by the laws of the State of California, U.S.A. without regard to its conflict of laws provisions.  The federal and state courts sitting in San Mateo County, California, U.S.A. will have proper and exclusive jurisdiction and venue with respect to any disputes arising from or related to the subject matter of this Agreement, provided that either party may seek injunctive relief in any court of competent jurisdiction.  User agrees to participate in press announcements, case studies, trade shows, or other forms reasonably requested by Opsee.  Opsee is permitted to disclose that User is one of its testers to any third party at its sole discretion.</li>
            </ol>
            </Col>
          </Row>
        </Grid>
      </div>
    );
  }
});

export default BetaTOS;
